# Generated by Django 4.2.7 on 2023-11-05 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reportes',
            new_name='Reporte',
        ),
    ]
